# Uncomment the next line to define a global platform for your project
 platform :ios, '12.1'

target 'Cloude' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cloude

  target 'CloudeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CloudeUITests' do
    # Pods for testing
  end
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  
end
